language: python

sudo: false
cache:
    directories:
        - "~/.platformio"

before_install:
    - cd Esp32PmSensor

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

